"""
Steps every Regular-producing script runs last, so glyphs added late (T2's Latin
Extended-A and Vietnamese composites) get the same treatment as the T1 set:

  ss01 alternates for every accented a, and alternates.fea listing them
  mark-attachment anchors
  kerning-class membership

Idempotent: running it twice changes nothing.
"""
import os
import sys

import ufoLib2

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import anchors
import kerning

ALTERNATES_FEA = "sources/features/ui/alternates.fea"


def ss01_alternates(font):
    """An .ss01 alternate for every glyph that is an `a` plus marks. Returns the number added."""
    if "a.ss01" not in font:
        return 0
    added = 0
    for g in list(font):
        if not (g.components and g.components[0].baseGlyph == "a" and "." not in g.name):
            continue
        name = g.name + ".ss01"
        if name in font:
            continue
        alt = font.newGlyph(name)
        alt.width = g.width
        alt.components.append(ufoLib2.objects.Component(baseGlyph="a.ss01"))
        for c in g.components[1:]:
            alt.components.append(ufoLib2.objects.Component(
                baseGlyph=c.baseGlyph, transformation=c.transformation))
        added += 1
    return added


def write_alternates_fea(font, path=ALTERNATES_FEA):
    base = sorted(g.name[:-5] for g in font if g.name.endswith(".ss01") and g.name[:-5] in font)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as fh:
        fh.write("# alternates.fea - generated by tools/finalize.py, do not edit.\n")
        fh.write("# ss01: single-storey a, for a and every accented a.\n")
        fh.write("@ss01_base = [" + " ".join(base) + "];\n")
        fh.write("@ss01_alt = [" + " ".join(n + ".ss01" for n in base) + "];\n")
        fh.write("feature ss01 {\n    sub @ss01_base by @ss01_alt;\n} ss01;\n")


def finalize(font):
    """Returns (ss01 alternates added, anchors, kern pairs)."""
    added = ss01_alternates(font)
    write_alternates_fea(font)
    return added, anchors.add_anchors(font), kerning.apply(font)
